char scarletWitch[1000]="ScarletWitch : Welcome Mortal! I will be guiding you throughout your sad,pathetic journey";
char barbie[1000]="Barbie: Well, well, well. Looks like we've got ourselves a drama queen . Let's add some sparkle to this 'pathetic' journey! ";
char back[1000] = "As your consciousness slowly awakens, you become aware of an otherworldly transformation. The boundaries between dream and reality blur as you find yourself trapped in an unfamiliar form. In the quiet solitude of the room, a surreal reality unfolds. You gaze upon your new physique, a creature with numerous legs, delicate and grotesque. Panic and confusion set in as you try to comprehend this metamorphosis. The air feels different, and the surroundings, once familiar, now appear distorted. You, the player, are now a participant in this strange and unsettling tale, navigating a world that defies reason and challenges your very existence.";

char option1[1000] = "You really have one way to end it all: starve yourself. Your guide will be heavily disappointed, but who cares, right?";

char option2[1000] = "As a bug-college-student, you no longer perceive interconnectedness but an irreparable disconnection between your two worlds. Human interactions are a distant echo, drowned out by the cacophony of silent screams within your own mind.\n\nThe mysterious metamorphosis brought not enlightenment but a never-ending nightmare. Forces that lurked in the shadows, both human and insect, sought not to unravel secrets but to exploit vulnerabilities. The University, once a beacon of hope, became a breeding ground for cruelty. Secret societies and enigmatic figures weren't sources of intrigue but instruments of torment, blurring the lines between self and tormentor.\n\nIn the desolate corners of the library and the hidden chambers of Metropolis, your journey continued—a descent into a darkness that consumed both human aspirations and insect instincts. The insect realm didn't beckon; it swallowed you whole, revealing not prophecies but an abyss of hopelessness.";

char option2c[1000] = "In the cold glow of a computer screen, your metamorphosis as a bug-college-student took on a distinctly binary nature—alternating between the zeros of despair and the ones of fleeting hope. As a computer science student entangled in the web of your own existence, the challenges multiplied, echoing the complexities of the code you studied.";

char guide[1000] = "Your humble guide is very busy, but she sent you a letter that if you go on a quest to find the Holy Grail, she will send you to a place where you can finally be happy.";

char win[1000] = "Indeed, this is surprising. Brace yourself as we journey into a realm where the very fabric of reality is woven by the intricate dance of insects, a surprising tapestry where bugs hold dominion.";

char lose[1000] = "Your foolish requests fall on deaf ears. I have no inclination to aid or indulge in such trivial endeavors. The whims of insects and alternate realms matter not to me; my focus lies elsewhere. Do not test my patience further.";
char first[1000] = "In a town, there is a barber who shaves all men who do not shave themselves and only those men. The question is, does the barber shave himself? If he does, then he shouldn't, but if he doesn't, then he should. What is the answer?";
char second[1000] = "A plane crashes on the border of the United States and Canada. Where do they bury the survivors? ";
char third[1000] = "The more you look at it, the less you see. What is it?";
char fourth[1000] = "What comes once in a minute, twice in a moment, but never in a thousand years?";
char intro[1000] = "Embarking on an expedition through the mystical Riddlewood Forest, you find yourself at the mercy of whimsical puzzles that guard its ancient secrets. The towering trees seem to whisper riddles, challenging any who dare to traverse their wooded domain. To journey through this captivating forest, one must unlock the answers hidden within the enigmatic puzzles that dance amid the foliage. Each correct response unravels the path forward, unveiling the mysteries that lie beneath the canopy of the Riddlewood Forest.";
char moral[1000] = "As you step into the mystical realm of Moral Crossroads, the ethereal presence of the Moraliths envelops you. These wise and enigmatic beings, guardians of ethical balance, greet you with an otherworldly resonance. Their voices echo through the air, foretelling of the trials ahead. 'Seeker of the Holy Grail, prepare thyself for the dilemmas that shall shape your destiny. In the heart of Moral Crossroads, your choices shall carve the path to salvation or tribulation. Choose wisely, for the very fabric of your morality hangs in the balance.'";
char ethical1[1000] = "you decide the fate of one stained by grave deeds. Mercy may breed redemption, but danger lingers. Opting for justice eliminates immediate threats, yet vengeance whispers in its wake. The balance between forgiveness and accountability teeters on a precipice. Your choice echoes through realms, shaping destinies, a weighty decision in the haunting corridors of morality.";
char ethical2[1000] = "Amidst the looming threat of the world's demise, you find yourself facing a harrowing ethical dilemma. A group has discovered a potential solution to avert the impending catastrophe, but it involves sacrificing a small, innocent child to activate the mechanism. On one hand, the sacrifice could save countless lives and preserve the world. On the other hand, the moral weight of intentionally causing harm to an innocent child is a heavy burden. As the seconds tick away, you must grapple with the profound ethical quandary of choosing between the greater good and the intrinsic value of an individual life.";
char ethical3[1000] = "In the heart of a technological breakthrough, you confront an ethical crossroads. A brilliant scientist has developed a groundbreaking artificial intelligence system that could revolutionize medicine, eradicate poverty, and solve pressing global issues. However, the catch is that the system requires constant access to personal data from every individual on the planet. The dilemma unfolds as you weigh the potential for immense societal progress against the invasion of privacy and the potential misuse of sensitive information. The question becomes whether the pursuit of collective welfare justifies sacrificing individual privacy and autonomy.";
char mount[1000]="As you ascend the Mount of Sisyphus, a daunting task awaits. A massive boulder rests at the base, and your mission is to roll it to the mountain's peak. With each arduous push, the boulder inches closer to the summit. Yet, just as success seems within reach, an unseen force sends it tumbling back down. The cycle repeats—a relentless struggle against futility. The challenge tests not just your physical strength but your resolve to persist in the face of a seemingly endless task, echoing the existential journey of Sisyphus himself.";
char mountwin[1000]="You are smarter than you look really...You chose not to participate in a unneccesary task.It is  okay to give up.But to your surprise the Holy Grail appears it seems that the Gods have mercy on you";
char mountlose[1000]="You just got played by Sisyphus. He has once again defied the Gods. Now you're stuck pushing a boulder up a mountain for eternity. But Hey! better than being a college student right?";
char barbieland[1000]="As you enter BarbieLand Barbie, the bug queen of BarbieLand, approaches you with a somber request: solve the murder mystery of her mermaid friend, Luna Waves. Luna's lifeless body was discovered in the moonlit garden, and the enchanting night now conceals secrets that only your keen insect senses can unveil.";
char suspects[1000] = "Murder Mystery: Whispers in the Moonlit Garden\n\n\
Clues:\n\n\
1. The Torn Love Letter\n\
2. Footprints in the Moonlight\n\n\
Suspects:\n\n\
1. Stella, the Shy Starfish:\n\
   Alibi: Claims to have been stargazing alone on the far side of the garden.\n\
2. Oceanus, the Mysterious Seahorse:\n\
   Alibi: Insists on swimming through the enchanted coral maze.\n\
3. Lumina, the Luminous Firefly:\n\
   Alibi: States she was illuminating Barbie's Grand Dollhouse.";

char barbiewin[1000] = "Barbie is very happy because you helped and insists that you stay in her BarbieLand forever";
char college1[1000]="Amidst the human hustle of a vibrant college campus, you, an unusual and intellectually gifted bug, navigate the bustling halls of academia. Once human, an inexplicable metamorphosis has reduced you to insect proportions, yet your intellect remains undiminished. Unfazed by your tiny stature, you embrace the challenges of being a computer science student in a world dominated by humans.You wake up at sharp 6 o clock,luckily the biological clock of a bug does not let you leep till noon";
char codep3[1000]"Decrypt this : Vg'f n tbbq gvzr gb unir n pbeerpg vqrn, frrx naq yvir jvgu gur zvfg.";
char codep2[1000]="Decipher the meaning : @ # % $ * & ! ^ ~ ? + = /";
char codep1[1000]="Convert to ASCII : 01001000 01100101 01101100 01101100 01101111 00101100 00100000 01000010 01110101 01100111 00100001 ";
